In [1]:
"""
Series
'Series'는 1차원 배열과 유사한 구조를 가지며, 단일 데이터 타입의 값을 가짐.
각 값에는 고유한 인덱스가 할당되어 있어, 인덱스를 통해 개별 데이터에 접근.
"""

"\nSeries\n'Series'는 1차원 배열과 유사한 구조를 가지며, 단일 데이터 타입의 값을 가짐.\n각 값에는 고유한 인덱스가 할당되어 있어, 인덱스를 통해 개별 데이터에 접근.\n"

In [53]:
import pandas as pd #설치가 안되어 있어 오류

data1 = [1,2,3,4,5]
series = pd.Series(data1)

print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [3]:
pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/29/d4/1244ab8edf173a10fd601f7e13b9566c1b525c4f365d6bee918e68381889/pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/b7/98/5640a09daa3abf0caeaefa6e7bf0d10c0aa28a77c84e507d6a716e0e23df/numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     -------------------------------------- 59.7/59.7 kB 634.7 kB/s eta 0:00:00
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tzdata>=2022.7 from https://files.python


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
python - m pip install --upgrade pip #이건 여기다가 아니라 cmd에

SyntaxError: invalid syntax (1104317531.py, line 1)

In [54]:
import pandas as pd #설치가 안되어 있어 오류

data2 = [1,2,3,4,5]
series = pd.Series(data2)

print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [9]:
"""
DataFrame
'DataFrame'은 2차원 레이블이 붙은 데이터 구조로, SQL 테이블이나 엑셀 스프레드시트와 비슷한 형태입니다. 서로 다른 데이터 타입의 열을 갖을 수 있으며, 각 열은 'Series'객체입니다.
"""

"\nDataFrame\n'DataFrame'은 2차원 레이블이 붙은 데이터 구조로, SQL 테이블이나 엑셀 스프레드시트와 비슷한 형태입니다. 서로 다른 데이터 타입의 열을 갖을 수 있으며, 각 열은 'Series'객체입니다.\n"

In [60]:
pd.set_option('display.max_columns', None)  # 열 개수 제한 해제
pd.set_option('display.width', 1000)         # 출력 너비를 100으로 설정
data3 = {
    'Name' : ['pool', 'kay', 'dean', 'kai'],
    'Age' : [1, 2, 3, 4],
    'City' : ['New York', 'Paris', 'korea', 'japan']
}
df = pd.DataFrame(data3)

print(df)

   Name  Age      City
0  pool    1  New York
1   kay    2     Paris
2  dean    3     korea
3   kai    4     japan


In [62]:
pd.set_option('display.max_columns', None)  # 열 개수 제한 해제
pd.set_option('display.width', 1000)         # 출력 너비를 100으로 설정
pd.set_option('display.max_colwidth', 1000)  # 열 너비를 충분히 크게 설정

data4 = [[1,2,3,4,5], [1,2,3,4,5]]
series = pd.Series(data4)

print(series)

0    [1, 2, 3, 4, 5]
1    [1, 2, 3, 4, 5]
dtype: object


In [63]:
data = {1,2,3,4,5}
series = pd.Series(data)

print(series)

TypeError: 'set' type is unordered

In [15]:
"""
data = {1, 2, 3, 4, 5}은 **집합(set)**입니다. 집합은 순서가 없는 자료형이므로, 이를 pandas.Series로 변환할 때 순서가 중요한 시리즈로 변환하려면 순서를 보장할 수 있는 자료형(리스트나 튜플)로 변환
"""

'\ndata = {1, 2, 3, 4, 5}은 **집합(set)**입니다. 집합은 순서가 없는 자료형이므로, 이를 pandas.Series로 변환할 때 순서가 중요한 시리즈로 변환하려면 순서를 보장할 수 있는 자료형(리스트나 튜플)로 변환\n'

In [64]:
data = pd.read_csv('data5.csv')

In [65]:
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_colwidth', 10)
pd.set_option('display.width', 10)

In [66]:
data

name  \
0   john   
1    Ace   
2  emily   

   age  \
0   25   
1   20   
2   22   

  Sex  
0   M  
1   M  
2   F

In [67]:
"""
display.max_rows : 출력할 최대 행의 수를 설정
display.max_columns : 출력할 최대 열의 수를 설정
display.max_colwidth : 최대 문자의 수를 설정
display.width : 콘솔 출력 시, 출력할 때의 전체 페이지 너비를 설정

"""

'\ndisplay.max_rows : 출력할 최대 행의 수를 설정\ndisplay.max_columns : 출력할 최대 열의 수를 설정\ndisplay.max_colwidth : 최대 문자의 수를 설정\ndisplay.width : 콘솔 출력 시, 출력할 때의 전체 페이지 너비를 설정\n\n'

In [72]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[2,4,6],[3,6,9]])

print(a)
print(b)

[1 2 3]
[[2 4 6]
 [3 6 9]]
